name: Generate label in pr

on:
  - pull_request

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        token: ${{ secrets.GH_TOKEN }}
  
    - name: Adicionar Label
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const labelsToAdd = ["Waiting Validate by QA/PO"];
          await github.issues.addLabels({
          owner: context.repo.owner,
          repo: context.repo.repo,
          issue_number: context.issue.number,
          labels: labelsToAdd
          });
