name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        token: ${{ secrets.GH_TOKEN }}

    - name: Get Current Branch Name
      run: |
        CURRENT_BRANCH=${{ github.ref }}
        echo "Current branch: $CURRENT_BRANCH"
        echo "{current_branch}=={$CURRENT_BRANCH}" >> $GITHUB_OUTPUT

      id: current_branch
  
    - name: UpDocker
      run: docker-compose up -d
   
    - name: Build 
      run: go build -v
      
    - name: Current Branch Test Coverage
      run: GIN_MODE=release go test -race -v -coverpkg=./controllers >> coverage-out.txt

    - name: Main Branch Test Coverage
      run: | 
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch
        git checkout main

        GIN_MODE=release go test -race -v -coverpkg=./controllers >> coverage-out.txt
        

    - name: Generate Main Branch Coverage Percent
      run: |
        PENULTIMA_LINHA=$(tac coverage-out.txt | sed -n 2p)
        MAINCOV=$(echo "$PENULTIMA_LINHA" | grep -oE '[0-9]+\.?[0-9]*')

  
    - name: Generate Current Branch Coverage Percent
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout ${{ steps.current_branch.outputs.current_branch }}


        PENULTIMA_LINHA=$(tac coverage-out.txt | sed -n 2p)
        BRANCHCOV=$(echo "$PENULTIMA_LINHA" | grep -oE '[0-9]+\.?[0-9]*')
        echo "maincov = $MAINCOV"
        echo "branchvoc = $BRANCHCOV"
        if (( $(echo "$BRANCHCOV" -lt "$MAINCOV" | bc -l) )); then
          COLOR=red
          printf "\033[0;31mCode coverage %.1f%% is less than required %.1f%%\033[0m\n" $BRANCHCOV $MAINCOV
          exit -1
        else
          COLOR=green
          printf "\033[0;32mCode coverage is %.1f%%\033[0m\n" $BRANCHCOV
        fi
        
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch
        git checkout badge -f
        curl "https://img.shields.io/badge/coverage-$BRANCHCOV%25-$COLOR" > badge.svg
        git add badge.svg
        git commit -m "change badge" || true
        git push origin badge
