name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        token: ${{ secrets.GH_TOKEN }}

    - name: UpDocker
      run: docker-compose up -d
   
    - name: Build 
      run: go build -v

    - name: Test
      run: GIN_MODE=release go test -race -v -coverpkg=./controllers >> coverage.txt

    - run: | 
        COVERAGE_GATE=60
        LAST_LINE=$(tac coverage.txt | sed -n 2p)
        CODE_COVERAGE=$(echo "$LAST_LINE" | grep -oE '[0-9]+\.?[0-9]*')
        
        if (( $(echo "$CODE_COVERAGE < $COVERAGE_GATE" | bc -l) )) ; then
          COLOR=red
        elif (( $(echo "$COVERAGE >= $COVERAGE_GATE" | bc -l) )); then
          COLOR=green
        fi
        
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch
        git checkout badge -f
        curl "https://img.shields.io/badge/coverage-$CODE_COVERAGE%25-$COLOR" > badge.svg
        git add badge.svg
        git commit -m "change badge" || true
        git push origin badge
