name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    
    - name: UpDocker
      run: docker-compose up -d
   
    - name: Build 
      run: go build -v

    - name: Test
      run: GIN_MODE=release go test -v -v -coverpkg=./controllers
    
    - run: |
        make coverage > temp.out
        COVERAGE=$(tail -n 1 temp.out)
        echo $COVERAGE
        COLOR=orange
        if (( $(echo "$COVERAGE <= 50" | bc -l) )) ; then
          COLOR=red
          elif (( $(echo "$COVERAGE > 80" | bc -l) )); then
          COLOR=green
        fi
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout badge -f
        curl "https://img.shields.io/badge/coverage-$COVERAGE%25-$COLOR" > badge.svg
        git add badge.svg
        git commit -m "change badge" || true
        git push origin badge
