name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        token: ${{ secrets.GH_TOKEN }}
  
    - name: UpDocker
      run: docker-compose up -d
   
    - name: Build 
      run: go build -v
  
    - name: Generate Coverage Percent
      run: |
        GIN_MODE=release go test -race -v -coverpkg=./controllers >> coverage-out.txt
        
        PENULTIMA_LINHA=$(tac coverage-out.txt | sed -n 2p)
        BRANCHCOV=$(echo "$PENULTIMA_LINHA" | grep -oE '[0-9]+\.?[0-9]*')

        COVERAGE_GATE="87.1"
        if (( $(echo "$BRANCHCOV" -lt "$COVERAGE_GATE" | bc -l) )); then
          COLOR=red
          printf "\033[0;31mCode coverage %.1f%% is less than required %.1f%%\033[0m\n" $BRANCHCOV $COVERAGE_GATE
          exit -1
        else
          COLOR=green
          printf "\033[0;32mCode coverage is %.1f%%\033[0m\n" $BRANCHCOV 
        fi
        
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch
        git checkout badge -f
        curl "https://img.shields.io/badge/coverage-$BRANCHCOV%25-$COLOR" > badge.svg
        git add badge.svg
        git commit -m "change badge" || true
        git push origin badge
