# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

---
name: Test Coverage
on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Coverage
    runs-on: runner-shared-build
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          go-version-file: go.mod
      - run: eval ${{ env.CONFIG_TOKEN }}
      - run: |
          make coverage > temp.out
          COVERAGE=$(tail -n 1 temp.out)
          echo $COVERAGE
          COLOR=orange
          if (( $(echo "$COVERAGE <= 50" | bc -l) )) ; then
              COLOR=red
              elif (( $(echo "$COVERAGE > 80" | bc -l) )); then
              COLOR=green
          fi
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout badge -f
          curl "https://img.shields.io/badge/coverage-$COVERAGE%25-$COLOR" > badge.svg
          git add badge.svg
          git commit -m "change badge" || true
          git push origin badge
