name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        token: ${{ secrets.GH_TOKEN }}

    - name: UpDocker
      run: docker-compose up -d
   
    - name: Build 
      run: go build -v

    - name: Test
      run: GIN_MODE=release go test -race -v -coverpkg=./controllers >> coverage-out.txt

    - run: |
        PENULTIMA_LINHA=$(tac coverage-out.txt | sed -n 2p)
        COBERTURA=$(echo "$PENULTIMA_LINHA" | grep -oE '[0-9]+\.?[0-9]*')
        COLOR=orange
        if (( $(echo "$COBERTURA <= 50" | bc -l) )); then
          COLOR=red
        elif (( $(echo "$COBERTURA > 80" | bc -l) )); then
          COLOR=green
        fi
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b badge -f
        curl "https://img.shields.io/badge/coverage-$COBERTURA%25-$COLOR" > badge.svg
        git add badge.svg
        git commit -m "change badge" || true
        git push origin badge
        
        rm -f coverage-out.txt
        rm -f go-api-rest.git
