name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        token: ${{ secrets.GH_TOKEN }}

    - name: Get Current Branch Name
      run: |
        CURRENT_BRANCH=${{ github.ref }}
        echo "Current branch: $CURRENT_BRANCH"
  
    - name: UpDocker
      run: docker-compose up -d
   
    - name: Build 
      run: go build -v
      
    - name: Current Branch Test Coverage
      run: GIN_MODE=release go test -race -v -coverpkg=./controllers >> coverage-out.txt

    - name: Main Branch Test Coverage
      run: | 
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch
        git checkout main

        GIN_MODE=release go test -race -v -coverpkg=./controllers >> coverage-out.txt

    - name: Generate Main Branch Coverage Percent
      run: |
        PENULTIMA_LINHA=$(tac coverage-out.txt | sed -n 2p)
        MAINCOV=$(echo "$PENULTIMA_LINHA" | grep -oE '[0-9]+\.?[0-9]*')

  
    - name: Generate Current Branch Coverage Percent
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch
        git checkout $CURRENT_BRANCH"  


        PENULTIMA_LINHA=$(tac coverage-out.txt | sed -n 2p)
        COVERAGE=$(echo "$PENULTIMA_LINHA" | grep -oE '[0-9]+\.?[0-9]*')
        COLOR=orange
        if (( $(echo "$BRANCHCOV <= $MAINCOV" | bc -l) )); then
          COLOR=red
        elif (( $(echo "$BRANCHCOV > $MAINCOV" | bc -l) )); then
          COLOR=green
        fi
        
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch
        git checkout badge -f
        curl "https://img.shields.io/badge/coverage-$BRANCHCOV%25-$COLOR" > badge.svg
        git add badge.svg
        git commit -m "change badge" || true
        git push origin badge
